name: Unit Testing

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  unit-test:
    name: Jest Testing
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: "20.11.0"
      - run: npm install
      - run: npm run test
  
